version: '3.5'
networks:
  altouch_net:
    external: true # Join an existing Docker network
services:
  db-postgres:
    image: postgres:14-bullseye
    container_name: db-postgres
    env_file:
      - .env
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      altouch_net:
        ipv4_address: 172.20.11.100
  adminer:
    image: adminer
    container_name: db-adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      altouch_net:
        ipv4_address: 172.20.11.101
